### ISSUE TITLE
Be able to use url helpers in components without prefix

### ISSUE THREAD

**Issue by kitop** [jgnatch/mountain_view#17]
From #16
> I can't use URL's inside components without prefixing them with `main_app`

We should be able to use url helpers without any prefix, just like a normal app.

Probably has something to do with `isolate_namespace`.

**Comment by kitop** [comment]
Closed in #18

**Comment by jgnatch** [comment]
Hey @Fodoj it is now possible to use url helpers inside components without having to add the prefix `main_app`

Cheers!

**Comment by julianrubisch** [comment]
How can I make this work in the _styleguide_?

I'm probably just missing a piece of configuration  here...

**Comment by kitop** [comment]
Hi @julianrubisch, can you share an example of what you're trying to do and the error you're getting (if any)?

**Comment by julianrubisch** [comment]
thanks for the reply... just when I wanted to reproduce, the issue was gone... probably an un-reloaded initializer or sthg... nevermind, sorry!
