### ISSUE TITLE
Bourbon

### ISSUE THREAD

**Issue by gazaston** [jgnatch/mountain_view#20]
Hey,

I can't figure out a way to use Bourbon mixins in my components' sass files… any suggestions?

**Comment by kitop** [comment]
@gazaston doing `@import 'bourbon';` at the beginning of the sass files should work. 
Have you tried that? If so and not working, are you getting any error?

**Comment by gazaston** [comment]
Hey, that worked fine — I have a fairly custom set of default stylesheets I like to use, and I just needed to tweak the import order a bit.
