### ISSUE TITLE
Global components styles/js

### ISSUE THREAD

**Issue by jgnatch** [jgnatch/mountain_view#6]
It would be nice to share some common styles on every component.

**Comment by jgnatch** [comment]
Closed on #15

**Comment by gazaston** [comment]
It would be great to make jquery globally available to all components, too.

**Comment by kitop** [comment]
@gazaston good idea! I think something similar to what was done with stylesheets in #15 would work, right?

**Comment by gazaston** [comment]
I guess so. For now, I've added a file `app/assets/javascripts/mountain_view/styleguide.js` and added the line `//= require jquery`. Works fine.
